### ISSUE TITLE
CIVET-output compatibility?

### ISSUE THREAD

**Issue by sdrakulich** [cwatson/brainGraph#6]
Greetings,

I'm hoping to understand if your tool is compatible, or could be made compatible with McGill's CIVET tool.
http://www.bic.mni.mcgill.ca/ServicesSoftware/CIVET-2-1-0-Table-of-Contents

Thank you!

**Comment by sdrakulich** [comment]
Data that I'd need to use is in the structure
- subjectfolder
-- surfaces
with associated txt files containing ~40k rows with values; two files because left and right hemisphere
-- thickness
volume and surface area txt files as described above

I think it might be best to show you another approach, by [Keith Worsley for SurfStat](http://www.math.mcgill.ca/keith/surfstat/), a "Matlab toolbox for the statistical analysis of univariate and multivariate surface and volumetric data using linear mixed effects models and random field theory".

Masks are created by having those values set to zero in the appropriate places.

[There is some vague implementation ](http://www.bic.mni.mcgill.ca/ServicesSoftware/StatisticalAnalysesUsingR)of such analyses within the institution, but they are not fleshed out it seems.

The reason I ask is because I'd infinitely prefer (at this stage of my learning) staying in the R ecosystem.

Thank you so much for the help!

**Comment by cwatson** [comment]
Are you planning on analyzing structural covariance networks? If there are ~40K vertices per hemisphere, then the correlation matrix for a single subject would be `8e4 x 8e4` in size, which would be ~51 GB of memory! 

I would have to change most aspects of the package in order to accommodate such data, as it is designed to work with networks with 1-2K vertices (maybe more). However, if you are looking to just do surface-based analyses, then I won't be able to help. You can see other MRI-related R packages [here](https://cran.r-project.org/web/views/MedicalImaging.html).

**Comment by cwatson** [comment]
I'm going to close this issue as it seems unrelated to what the package does.
